---
meta:
  github:
    website:
      uri: git@github.com:shieldproject/website
      branch: ci
      private_key:  (( vault "secret/pipelines/shared/shield-bot/github:private" ))
      access_token: (( vault "secret/pipelines/shared/shield-bot/github:access_token" ))

    starkandwayne:
      access_token: (( vault "secret/pipelines/shared/shield-bot/github:access_token" ))

jobs:
  - name: build
    plan:
      - aggregate:
        - get: git
          trigger: true
        - get: shield-code
          trigger: true
        - get: releases
          trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: davidlohle/concourse-hugo
              tag:        latest
          inputs:
            - name: git
            - name: shield-code
            - name: releases
          outputs:
            - name: pushme
          run:
            path: ./git/ci/scripts/build
            args: []
          params:
            CF_API_URL:  https://api.run.pivotal.io
            CF_USERNAME: (( vault "secret/pivotal/bot:username" ))
            CF_PASSWORD: (( vault "secret/pivotal/bot:password" ))
            CF_ORG:      starkandwayne
            CF_SPACE:    shieldproject
            REPO_ROOT: git
            REPO_OUT: pushme
            BRANCH: ((grab meta.github.website.branch))
      - put: git
        params:
          rebase: true
          repository: pushme/git
  - name: staging
    plan:
    - aggregate:
      -  get: git
         passed: [build]
         trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: starkandwayne/concourse
            tag:        latest
        inputs:
          - name: git
        run:
          path: ./git/ci/scripts/stage
          args: []
        params:
          CF_API_URL:  https://api.run.pivotal.io
          CF_USERNAME: (( vault "secret/pivotal/bot:username" ))
          CF_PASSWORD: (( vault "secret/pivotal/bot:password" ))
          CF_ORG:      starkandwayne
          CF_SPACE:    shieldproject
          MANIFEST:    manifest-stage.yml
  - name: prod
    plan:
      - aggregate:
        - { get: git, passed: [staging] }
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: starkandwayne/concourse
              tag:        latest
          inputs:
            - name: git
          run:
            path: ./git/ci/scripts/stage
            args: []
          params:
            CF_API_URL:  https://api.run.pivotal.io
            CF_USERNAME: (( vault "secret/pivotal/bot:username" ))
            CF_PASSWORD: (( vault "secret/pivotal/bot:password" ))
            CF_ORG:      starkandwayne
            CF_SPACE:    shieldproject
            MANIFEST:    manifest.yml





resources:
  - name: git
    type: git
    source:
      uri:         (( grab meta.github.website.uri ))
      branch:      (( grab meta.github.website.branch ))
      private_key: (( grab meta.github.website.private_key ))

  - name: shield-code
    type: git
    source:
      uri: https://github.com/starkandwayne/shield
      branch: website-ci

  - name: releases
    type: github-release
    source:
      user:         starkandwayne
      repository:   shield
      access_token: (( grab meta.github.starkandwayne.access_token ))
