---
meta:
  github:
    website:
      uri: git@github.com:shieldproject/website
      branch: master
      private_key:  (( vault "secret/pipelines/shared/shield-bot/github:private" ))
      access_token: (( vault "secret/pipelines/shared/shield-bot/github:access_token" ))

    starkandwayne:
      access_token: (( vault "secret/pipelines/shared/shield-bot/github:access_token" ))

  slack:
    webhook: (( vault "secret/slack/botspam:webhook" ))
    channel: '#botspam'
    username:      starkandwayne-ci
    icon:          https://www.starkandwayne.com/assets/images/shield-blue-50x50.png

jobs:
  - name: build
    plan:
      - aggregate:
        - get: git
          trigger: true
        - get: releases
          trigger: true
        - get: blog
          trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: huntprod/verse
              tag:        latest
          inputs:
            - name: git
            - name: releases
            - name: blog
          outputs:
            - name: pushme
          run:
            path: ./git/ci/scripts/build
            args: []
          params:
            BLOG_IN:     blog
            CF_API_URL:  https://api.run.pivotal.io
            CF_USERNAME: (( vault "secret/pivotal/bot:username" ))
            CF_PASSWORD: (( vault "secret/pivotal/bot:password" ))
            CF_ORG:      starkandwayne
            CF_SPACE:    shieldproject
            REPO_ROOT: git
            REPO_OUT: pushme
            BRANCH: ((grab meta.github.website.branch))
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     'The shieldproject.io failed to build. <https://10.200.131.2.netip.cc/teams/main/pipelines/shieldproject.io|More information.>'
      - put: git
        params:
          rebase: true
          repository: pushme/git
  - name: staging
    plan:
    - aggregate:
      -  get: git
         passed: [build]
         trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: huntprod/verse
            tag:        latest
        inputs:
          - name: git
        run:
          path: ./git/ci/scripts/stage
          args: []
        params:
          CF_API_URL:  https://api.run.pivotal.io
          CF_USERNAME: (( vault "secret/pivotal/bot:username" ))
          CF_PASSWORD: (( vault "secret/pivotal/bot:password" ))
          CF_ORG:      starkandwayne
          CF_SPACE:    shieldproject
          MANIFEST:    manifest-stage.yml
      on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     'The shieldproject.io failed to push to staging. <https://10.200.131.2.netip.cc/teams/main/pipelines/shieldproject.io|More information.>'
      on_success:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     'An updated shieldproject.io has been successfully built and pushed to <http://staging.shieldproject.io|staging>. <https://10.200.131.2.netip.cc/teams/main/pipelines/shieldproject.io|Push to prod?>'
  - name: prod
    plan:
      - aggregate:
        - { get: git, passed: [staging] }
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: huntprod/verse
              tag:        latest
          inputs:
            - name: git
          run:
            path: ./git/ci/scripts/stage
            args: []
          params:
            CF_API_URL:  https://api.run.pivotal.io
            CF_USERNAME: (( vault "secret/pivotal/bot:username" ))
            CF_PASSWORD: (( vault "secret/pivotal/bot:password" ))
            CF_ORG:      starkandwayne
            CF_SPACE:    shieldproject
            MANIFEST:    manifest.yml
        on_failure:
          put: notify
          params:
            channel:  (( grab meta.slack.channel ))
            username: (( grab meta.slack.username ))
            icon_url: (( grab meta.slack.icon ))
            text:     'The shieldproject.io push to production failed. <https://10.200.131.2.netip.cc/teams/main/pipelines/shieldproject.io|More information here.'
        on_success:
            put: notify
            params:
              channel:  (( grab meta.slack.channel ))
              username: (( grab meta.slack.username ))
              icon_url: (( grab meta.slack.icon ))
              text:     'The shieldproject.io push to production succeeded. <http://shieldproject.io|View here.>'


resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: rss
  type: docker-image
  source:
    repository: starkandwayne/rss-resource




resources:
- name: git
  type: git
  source:
    uri:         (( grab meta.github.website.uri ))
    branch:      (( grab meta.github.website.branch ))
    private_key: (( grab meta.github.website.private_key ))

- name: releases
  type: github-release
  source:
    user:         starkandwayne
    repository:   shield
    access_token: (( grab meta.github.starkandwayne.access_token ))

- name: notify
  type: slack-notification
  source:
    url: (( grab meta.slack.webhook ))

- name: blog
  type: rss
  source:
    url: http://www.starkandwayne.com/blog/tag/shield/rss/
